image_paths:
  objects_path: images/objects
  stream_path: images/stream

<<<<<<< HEAD
# Car address
car_address: "172.20.10.4"

# Detection confidence
detection_confidence: 0.3
=======
>>>>>>> 73617dabc4cd33e7e16fe2cef0824ff3f328ebeb
retry_attempts: 20
